package com.example.buddy_match.model;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import java.util.Date;
import lombok.Data;
import org.hibernate.annotations.DynamicInsert;

@Data
@Entity
@DynamicInsert
public class Team {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team.id
     *
     * @mbg.generated Sat Jan 25 15:41:16 CST 2025
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team.description
     *
     * @mbg.generated Sat Jan 25 15:41:16 CST 2025
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team.max_num
     *
     * @mbg.generated Sat Jan 25 15:41:16 CST 2025
     */
    private Integer maxNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team.expire_time
     *
     * @mbg.generated Sat Jan 25 15:41:16 CST 2025
     */
    private Date expireTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team.user_id
     *
     * @mbg.generated Sat Jan 25 15:41:16 CST 2025
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team.create_time
     *
     * @mbg.generated Sat Jan 25 15:41:16 CST 2025
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team.update_time
     *
     * @mbg.generated Sat Jan 25 15:41:16 CST 2025
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team.is_delete
     *
     * @mbg.generated Sat Jan 25 15:41:16 CST 2025
     */
    private Byte isDelete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team.team_status
     *
     * @mbg.generated Sat Jan 25 15:41:16 CST 2025
     */
    private Byte teamStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team.has_join_num
     *
     * @mbg.generated Sat Jan 25 15:41:16 CST 2025
     */
    private Byte hasJoinNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team.has_join
     *
     * @mbg.generated Sat Jan 25 15:41:16 CST 2025
     */
    private Byte hasJoin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team.avatar
     *
     * @mbg.generated Sat Jan 25 15:41:16 CST 2025
     */
    private String avatar;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team.team_name
     *
     * @mbg.generated Sat Jan 25 15:41:16 CST 2025
     */
    private String teamName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team.password
     *
     * @mbg.generated Sat Jan 25 15:41:16 CST 2025
     */
    private String password;
}