package com.example.buddy_match.model.atest;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.PrePersist;
import java.util.Date;
import lombok.Data;
import org.hibernate.annotations.DynamicInsert;

import com.example.buddy_match.anotation.SnowflakeIdGenerator;

@Data
@Entity
@DynamicInsert
public class BuddyUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ATest..buddy_user.id
     *
     * @mbg.generated Tue Feb 25 21:55:12 CST 2025
     */
    @Id
    @GeneratedValue 
    @SnowflakeIdGenerator(workerId=1, datacenterId=1)
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ATest..buddy_user.avatar
     *
     * @mbg.generated Tue Feb 25 21:55:12 CST 2025
     */
    private String avatar;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ATest..buddy_user.create_time
     *
     * @mbg.generated Tue Feb 25 21:55:12 CST 2025
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ATest..buddy_user.display_name
     *
     * @mbg.generated Tue Feb 25 21:55:12 CST 2025
     */
    private String displayName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ATest..buddy_user.is_delete
     *
     * @mbg.generated Tue Feb 25 21:55:12 CST 2025
     */
    private Byte isDelete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ATest..buddy_user.is_parent
     *
     * @mbg.generated Tue Feb 25 21:55:12 CST 2025
     */
    private Byte isParent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ATest..buddy_user.parent_id
     *
     * @mbg.generated Tue Feb 25 21:55:12 CST 2025
     */
    private Long parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ATest..buddy_user.password
     *
     * @mbg.generated Tue Feb 25 21:55:12 CST 2025
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ATest..buddy_user.personal_bio
     *
     * @mbg.generated Tue Feb 25 21:55:12 CST 2025
     */
    private String personalBio;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ATest..buddy_user.tag_name
     *
     * @mbg.generated Tue Feb 25 21:55:12 CST 2025
     */
    private String tagName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ATest..buddy_user.update_time
     *
     * @mbg.generated Tue Feb 25 21:55:12 CST 2025
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ATest..buddy_user.user_id
     *
     * @mbg.generated Tue Feb 25 21:55:12 CST 2025
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ATest..buddy_user.user_role
     *
     * @mbg.generated Tue Feb 25 21:55:12 CST 2025
     */
    private Byte userRole;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ATest..buddy_user.username
     *
     * @mbg.generated Tue Feb 25 21:55:12 CST 2025
     */
    private String username;
}