package com.example.buddy_match.model.atest;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.PrePersist;
import java.util.Date;
import lombok.Data;
import org.hibernate.annotations.DynamicInsert;

import com.example.buddy_match.anotation.SnowflakeIdGenerator;

@Data
@Entity
@DynamicInsert
public class TeamUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ATest..team_user.id
     *
     * @mbg.generated Tue Feb 25 21:55:12 CST 2025
     */
    @Id
    @GeneratedValue 
    @SnowflakeIdGenerator(workerId=1, datacenterId=1)
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ATest..team_user.create_time
     *
     * @mbg.generated Tue Feb 25 21:55:12 CST 2025
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ATest..team_user.is_delete
     *
     * @mbg.generated Tue Feb 25 21:55:12 CST 2025
     */
    private Byte isDelete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ATest..team_user.team_id
     *
     * @mbg.generated Tue Feb 25 21:55:12 CST 2025
     */
    private Long teamId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ATest..team_user.update_time
     *
     * @mbg.generated Tue Feb 25 21:55:12 CST 2025
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ATest..team_user.user_id
     *
     * @mbg.generated Tue Feb 25 21:55:12 CST 2025
     */
    private Long userId;
}