package com.example.buddy_match.model.atest;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.PrePersist;
import java.util.Date;
import lombok.Data;
import org.hibernate.annotations.DynamicInsert;

import com.example.buddy_match.anotation.SnowflakeIdGenerator;

@Data
@Entity
@DynamicInsert
public class Team {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ATest..team.id
     *
     * @mbg.generated Tue Feb 25 21:55:12 CST 2025
     */
    @Id
    @GeneratedValue 
    @SnowflakeIdGenerator(workerId=1, datacenterId=1)
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ATest..team.avatar
     *
     * @mbg.generated Tue Feb 25 21:55:12 CST 2025
     */
    private String avatar;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ATest..team.create_time
     *
     * @mbg.generated Tue Feb 25 21:55:12 CST 2025
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ATest..team.description
     *
     * @mbg.generated Tue Feb 25 21:55:12 CST 2025
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ATest..team.expire_time
     *
     * @mbg.generated Tue Feb 25 21:55:12 CST 2025
     */
    private Date expireTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ATest..team.has_join
     *
     * @mbg.generated Tue Feb 25 21:55:12 CST 2025
     */
    private Byte hasJoin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ATest..team.has_join_num
     *
     * @mbg.generated Tue Feb 25 21:55:12 CST 2025
     */
    private Byte hasJoinNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ATest..team.is_delete
     *
     * @mbg.generated Tue Feb 25 21:55:12 CST 2025
     */
    private Byte isDelete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ATest..team.max_num
     *
     * @mbg.generated Tue Feb 25 21:55:12 CST 2025
     */
    private Integer maxNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ATest..team.password
     *
     * @mbg.generated Tue Feb 25 21:55:12 CST 2025
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ATest..team.team_name
     *
     * @mbg.generated Tue Feb 25 21:55:12 CST 2025
     */
    private String teamName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ATest..team.team_status
     *
     * @mbg.generated Tue Feb 25 21:55:12 CST 2025
     */
    private Byte teamStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ATest..team.update_time
     *
     * @mbg.generated Tue Feb 25 21:55:12 CST 2025
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ATest..team.user_id
     *
     * @mbg.generated Tue Feb 25 21:55:12 CST 2025
     */
    private Long userId;
}