package com.example.buddy_match.mapper;

import com.example.buddy_match.model.BuddyUser;
import com.example.buddy_match.model.BuddyUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface BuddyUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buddy_user
     *
     * @mbg.generated Sat Jan 25 15:41:16 CST 2025
     */
    long countByExample(BuddyUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buddy_user
     *
     * @mbg.generated Sat Jan 25 15:41:16 CST 2025
     */
    int deleteByExample(BuddyUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buddy_user
     *
     * @mbg.generated Sat Jan 25 15:41:16 CST 2025
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buddy_user
     *
     * @mbg.generated Sat Jan 25 15:41:16 CST 2025
     */
    int insert(BuddyUser row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buddy_user
     *
     * @mbg.generated Sat Jan 25 15:41:16 CST 2025
     */
    int insertSelective(BuddyUser row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buddy_user
     *
     * @mbg.generated Sat Jan 25 15:41:16 CST 2025
     */
    List<BuddyUser> selectByExample(BuddyUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buddy_user
     *
     * @mbg.generated Sat Jan 25 15:41:16 CST 2025
     */
    BuddyUser selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buddy_user
     *
     * @mbg.generated Sat Jan 25 15:41:16 CST 2025
     */
    int updateByExampleSelective(@Param("row") BuddyUser row, @Param("example") BuddyUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buddy_user
     *
     * @mbg.generated Sat Jan 25 15:41:16 CST 2025
     */
    int updateByExample(@Param("row") BuddyUser row, @Param("example") BuddyUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buddy_user
     *
     * @mbg.generated Sat Jan 25 15:41:16 CST 2025
     */
    int updateByPrimaryKeySelective(BuddyUser row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buddy_user
     *
     * @mbg.generated Sat Jan 25 15:41:16 CST 2025
     */
    int updateByPrimaryKey(BuddyUser row);
}