package com.example.buddy_match.mapper;

import com.example.buddy_match.model.TeamUser;
import com.example.buddy_match.model.TeamUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface TeamUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table team_user
     *
     * @mbg.generated Sat Jan 25 15:41:16 CST 2025
     */
    long countByExample(TeamUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table team_user
     *
     * @mbg.generated Sat Jan 25 15:41:16 CST 2025
     */
    int deleteByExample(TeamUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table team_user
     *
     * @mbg.generated Sat Jan 25 15:41:16 CST 2025
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table team_user
     *
     * @mbg.generated Sat Jan 25 15:41:16 CST 2025
     */
    int insert(TeamUser row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table team_user
     *
     * @mbg.generated Sat Jan 25 15:41:16 CST 2025
     */
    int insertSelective(TeamUser row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table team_user
     *
     * @mbg.generated Sat Jan 25 15:41:16 CST 2025
     */
    List<TeamUser> selectByExample(TeamUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table team_user
     *
     * @mbg.generated Sat Jan 25 15:41:16 CST 2025
     */
    TeamUser selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table team_user
     *
     * @mbg.generated Sat Jan 25 15:41:16 CST 2025
     */
    int updateByExampleSelective(@Param("row") TeamUser row, @Param("example") TeamUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table team_user
     *
     * @mbg.generated Sat Jan 25 15:41:16 CST 2025
     */
    int updateByExample(@Param("row") TeamUser row, @Param("example") TeamUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table team_user
     *
     * @mbg.generated Sat Jan 25 15:41:16 CST 2025
     */
    int updateByPrimaryKeySelective(TeamUser row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table team_user
     *
     * @mbg.generated Sat Jan 25 15:41:16 CST 2025
     */
    int updateByPrimaryKey(TeamUser row);
}