package com.example.buddy_match.request;

import java.io.Serializable;
import java.util.Date;

import lombok.Data;

@Data
public class TeamQueryRequest implements Serializable {
  private static final long serialVerisonUID = 3191241232371631790L;

  /**
   *
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column team.id
   *
   * @mbg.generated Tue Jan 21 14:12:27 CST 2025
   */
  private Long id;

  /**
   *
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column team.description
   *
   * @mbg.generated Tue Jan 21 14:12:27 CST 2025
   */
  private String description;

  /**
   *
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column team.max_num
   *
   * @mbg.generated Tue Jan 21 14:12:27 CST 2025
   */
  private Integer maxNum;

  /**
   *
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column team.expire_time
   *
   * @mbg.generated Tue Jan 21 14:12:27 CST 2025
   */
  private Date expireTime;

  /**
   *
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column team.user_id
   *
   * @mbg.generated Tue Jan 21 14:12:27 CST 2025
   */
  private Long userId;

  /**
   *
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column team.create_time
   *
   * @mbg.generated Tue Jan 21 14:12:27 CST 2025
   */
  private Date createTime;

  /**
   *
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column team.update_time
   *
   * @mbg.generated Tue Jan 21 14:12:27 CST 2025
   */
  private Date updateTime;

  /**
   *
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column team.is_delete
   *
   * @mbg.generated Tue Jan 21 14:12:27 CST 2025
   */
  private Byte isDelete;

  /**
   *
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column team.team_status
   *
   * @mbg.generated Tue Jan 21 14:12:27 CST 2025
   */
  private Byte teamStatus;

  /**
   *
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column team.username
   *
   * @mbg.generated Tue Jan 21 14:12:27 CST 2025
   */
  private String username;

  /**
   *
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column team.password
   *
   * @mbg.generated Tue Jan 21 14:12:27 CST 2025
   */
  private String password;

  /**
   *
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column team.user_role
   *
   * @mbg.generated Tue Jan 21 14:12:27 CST 2025
   */
  private Byte userRole;

  /**
   *
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column team.gender
   *
   * @mbg.generated Tue Jan 21 14:12:27 CST 2025
   */
  private Byte gender;

  /**
   *
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column team.phone
   *
   * @mbg.generated Tue Jan 21 14:12:27 CST 2025
   */
  private String phone;

  /**
   *
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column team.email
   *
   * @mbg.generated Tue Jan 21 14:12:27 CST 2025
   */
  private String email;

  /**
   *
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column team.planet_code
   *
   * @mbg.generated Tue Jan 21 14:12:27 CST 2025
   */
  private String planetCode;

  /**
   *
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column team.tags
   *
   * @mbg.generated Tue Jan 21 14:12:27 CST 2025
   */
  private String tags;
  }

